services:
  # root-app:
  #   build: .
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app

  blog-app:
    build: .
    command: uvicorn blog.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    volumes:
      - .:/app
